project:
  type: website
  output-dir: docs

website:
  title: "Boon Chin Look"
  favicon: assets/sitelogo.PNG
  #back to top button - will get feedback and see should I create a button instead on it
  back-to-top-navigation: true
  navbar:
    logo: assets/sitelogo.PNG
    right:
        #text: Home
        #icon: house
      - href: projects/index.qmd
        text: Projects
        icon: paperclip

      - href: about.qmd
        text: About
        icon: people

      - icon: github
        href: https://github.com/BoonChinLook
        target: _blank
        
      - icon: file-earmark-pdf
        text: CV
        href: assets/Blankforcvtester.pdf
        target: _blank
  page-footer: 
    left: "Boon Chin Look, 2025"    
    right: "Built with [Quarto](https://quarto.org/)" 

        
format:
  html:
    theme: style.scss
    mainfont: Poppins
    toc: true
