---
title: "Botswana’s Economic Transformation Slides" 
author: 
    - "Assa Babissagana"
    - "Boon Chin Look"
    - "Daniela Groza"
    - "Fatima Contreiras"
date: "2024-10-20"
format: 
    revealjs:
        theme: simple
---
## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide1.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide2.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide3.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide4.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide6.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide7.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide8.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide9.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide10.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide11.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide12.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide13.PNG" background-size="100%"}

---

## {background-color="white" background-image="reports/botswana's_economic_transformation/botswana_slides/Slide14.PNG" background-size="100%"}
